### ISSUE TITLE
onPurchasesUpdated not called for pending purchase success

### ISSUE THREAD

**Issue by marchbold** [android/play-billing-samples#254] opened 2019-12-13 00:14 UTC
I have updated my application to use v2.1.0 (from an earlier 2.0.1 release) of the android play billing library and I am no longer receiving purchase updates on completion of a pending purchase.

I construct my billing client setting the listener to the current class, that implements `PurchasesUpdatedListener`:

```java
billingClient = BillingClient.newBuilder( getActivity() )
        .setListener( this )
        .enablePendingPurchases()
        .build();
```
I then launch a purchase and use the "slow test card approves after a few minutes"

```java
BillingFlowParams.Builder purchaseParamsBuilder = BillingFlowParams.newBuilder()
        .setSkuDetails( product );

billingClient.launchBillingFlow( getActivity(), purchaseParamsBuilder.build() );
```

My listener gets called after this indicating the purchase is pending:

```java
@Override
public void onPurchasesUpdated( BillingResult billingResult, List<Purchase> purchases )
{
    int responseCode = billingResult.getResponseCode();
    if (responseCode == BillingClient.BillingResponseCode.OK)
    {
        // I get to here with a Purchase.PurchaseState.PENDING 
    }
}
```

However this listener does NOT get called when the purchase completes. I leave the application open and I see the notification from the play store saying the purchase was successful in the notification bar. 

If I query the purchases manually after this notification I can get the updated purchase however this doesn't seem like a valid approach for handling the purchase.

Does anyone know what I am doing wrong or has this process changed?

**Comment by calren** [comment] 2019-12-16 19:10
@marchbold There should have been no changes regarding purchase updates in v2.1.0. 

I'm going to go ahead and close this issue since it's not an issue regarding the samples, but if you think there's a bug with the billing library itself, feel free to file an issue [here](https://issuetracker.google.com/issues/new?component=311487&template=1014446).

**Closed by calren** 2019-12-16 19:10 UTC

**Comment by TJClifton90** [comment] 2019-12-18 01:57
I am also seeing this issue. @marchbold did you find a solution?

**Comment by marchbold** [comment] 2019-12-19 05:22
No solution as yet! Glad I'm not the only one.

I've created an issue as requested [here](https://issuetracker.google.com/issues/146480197)

**Comment by TJClifton90** [comment] 2019-12-19 05:35
Yeah it's a bit of an annoying one.

I've basically ended up doing what you suggested. That is, I query the purchases at regular intervals and check for the pending purchase there. This may well be the intended behaviour, but the documentation certainly suggests that we should expect to get another callback when the state changes from pending to purchased. So I'm not sure whether it is the behaviour or the documentation that is incorrect.

**Comment by marchbold** [comment] 2019-12-19 07:13
Surely this isn't the intended behaviour?! but yeah I think I'm going to have to implement that as well. 

From memory, the previous releases of the library correctly called the updated handler correctly so hopefully this is fixed in an upcoming build.

**Comment by marchbold** [comment] 2019-12-19 07:20
@calren If you believe this issue to be handled in the samples, can you explain how the samples handle this scenario?

**Comment by marchbold** [comment] 2019-12-19 11:36
Any chance this is an issue with the PlayStore app not broadcasting an intent or something similar? I've gone back to an old version and still encountering this issue.

**Comment by calren** [comment] 2019-12-19 18:39
@marchbold @TJClifton90 this is not intended behavior. Is this only an issue when you upgrade from v2.0.1 to v2.1.0? Or is this a general issue regardless of the version of the Play Billing library?

**Comment by marchbold** [comment] 2019-12-19 22:52
Seems to be occurring with both 2.0.1 and 2.1.0 for me.

**Comment by CycleSkip** [comment] 2019-12-21 00:34
We have found the issue and made a fix for it. ETA 01/13/2020 to roll out to all devices.

**Comment by marchbold** [comment] 2019-12-25 22:10
Can you clarify what we need to do to apply this fix? Is this a fix for the play billing library or the play store app?

**Comment by CycleSkip** [comment] 2019-12-30 17:33
It's an issue in Play Store app so no fix will be needed from developers' side. New version of Play Store app will have the fix.
