### ISSUE TITLE
How to use TrivialDrive_v2 example ?

### ISSUE THREAD

**Issue by ashfaqahmed** [android/play-billing-samples#147] opened 2018-07-22 00:19 UTC
How to use TrivialDrive_v2 example for billing ? as i am unable to find any valid activity or fragment in it? no Androidmainifest.xml content as well ?

**Comment by yangwook** [comment] 2019-03-04 06:05
After import you have to provide keystore info & change APP_ID. When I run in andorid mobile device. It happended the following error. Would you let me know the reason of the following error?

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at com.jammysolution.inapptest.BaseGamePlayActivity.onCreate(BaseGamePlayActivity.java:148)
        at com.jammysolution.inapptest.MainActivity.onCreate(MainActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:7174)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
03-04

**Comment by calren** [comment] 2019-11-11 22:00
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440). Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).

**Closed by calren** 2019-11-11 22:00 UTC
Labels: TrivialDriveV2
