### ISSUE TITLE
What are the reason to cause IAB helper is not set up

### ISSUE THREAD

**Issue by huyongli** [android/play-billing-samples#115] opened 2018-01-17 03:27 UTC
My app happened IAB helper is not set up.
I don't know why InAppBillingService connected failure to cause this problem。

So， What are the reasons for the InAppBillingService  connection failure？

**Comment by FuckMicr0soft** [comment] 2019-07-25 15:54
You're using the "depecated" IAB system and Google wants you to upgrade to Google Play Billing. I have the same issues, but there are NO working java examples for GPB 2.0.1 ....

**Comment by isaidamier** [comment] 2019-08-20 19:10
Apologies for the issues you are experiencing. Might you be able to following the [TrivialDriveKotlin](https://github.com/googlesamples/android-play-billing/tree/master/TrivialDriveKotlin) sample in the meantime?

**Comment by calren** [comment] 2019-11-11 21:53
Closing this issue as TrivialDrive_v2 has now been [deprecated](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440)

**Closed by calren** 2019-11-11 21:53 UTC
Labels: TrivialDriveV2, play billing library

**Comment by DontTrustMicrosoft-MicrosoftIsAsshole** [comment] 2019-11-12 03:25
Cairen thinks it's a great idea to learn a new programming language because it suits Google anti java policy. The times we live in. Well I've been here before Android. Looks like I'm actually going to see it crash and burn and there's only one party responsible for it ...

**Comment by DontTrustMicrosoft-MicrosoftIsAsshole** [comment] 2019-11-12 03:48
https://imgur.com/a/GcFmUp8
The blue line is Kotlin interest. Google always has to learn the hard way. You can't force people into interest ( Google+, Wave, Glasses, Google Video) Kotlin is next. The problem is the scorched soil on the way out. You'll never get those developers back. Without developers you're nothing. You'll realize that when it's too late.
