### ISSUE TITLE
Removing Google sign in

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#383] opened 2020-10-19 17:15 UTC
Hi everyone. My app is related to children and Google does not let me use google sign in. I used this sample all along to develop my app. How to cancel google sign in and use regular email sign in?

This is Google's message: "We do not allow the use of any Google API that accesses Google Account data (including Google Sign-in and Google Play Games Services) in apps targeted to children."

I tried removing this line but still the app suggests the list of Gmail accounts during sign in:

```
private void triggerSignIn() {
        Log.d(TAG, "Attempting SIGN-IN!");
        List<AuthUI.IdpConfig> providers = new ArrayList<>();
        // Configure the different methods users can sign in
        providers.add(new AuthUI.IdpConfig.EmailBuilder().build());
        //providers.add(new AuthUI.IdpConfig.GoogleBuilder().build());

        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(providers)
                        .build(),
                RC_SIGN_IN);
    }
```
Any helps will be appreciated.

**Comment by vafaminato** [comment] 2020-10-20 02:01
I think I found the answer. I had to disable smart lock as well: .setIsSmartLockEnabled(false)

**Comment by calren** [comment] 2020-10-22 18:35
Closing this issue since it's resolved. Thanks for updating with how you resolved it! Smart lock does get tricky in certain cases, glad you were able to figure out that was the cause of your problem.

**Closed by calren** 2020-10-22 18:35 UTC
